apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-config
data:
  SPRING_APPLICATION_NAME: flight-reservation-api
  SPRING_DATASOURCE_URL: jdbc:postgresql://10.223.54.231:5544/flights_db
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
 